[package]
name = "ndsq-wedding"\nversion = "0.1.1"\nedition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.4.10", features = ["csr"] }
